config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'
}
  root to: 'performances#index'
  get 'performances/search'
  get 'performances/privacy'
  get '/users', to: 'users#a'
  post '/user/guest_sign_in', to: 'users#new_guest'

  resources :performances do
    resources :likes, only: %i[create destroy]
  end
  resources :users, only: :show
  resources :inquiries, only: [:new, :create]
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :performance
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    like = Like.create(performance_id: params[:performance_id], user_id: current_user.id)
    @performance = Performance.find(params[:performance_id])
  end

  def destroy
    @like = Like.find_by(performance_id: params[:performance_id], user_id: current_user.id)
    @performance = Performance.find(params[:performance_id])
    @like.destroy
  end
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/views/likes/_like.html.erb
 <div class="likes_buttons">
  <% if user_signed_in? %>
    <% if current_user.likes.find_by(performance_id: @performance.id)  %>
        <%=link_to 'いいねを外す' , performance_like_path(@performance.id,current_user.likes.find_by(performance_id: @performance.id).id), method: :delete, remote: true, class:"like-btn" %>
        <div class="likes-count">
          <%= @performance.likes.count%>
        </div>
      <% else %>
       <%=link_to 'いいね!をする', performance_likes_path(@performance.id), method: :post, remote: true, class:"like-btn" %>
       <div class="likes-count">
        <%= @performance.likes.count %>
      </div>
      <% end %>
    <% else %>
      <span class="like-btn-guest">いいね</span>
       <div class="likes-count">
       <%= @performance.likes.count %>
        </div>
   <% end %>

</div>

app/views/likes/create.js.erb
$('.likes_buttons').html("<%= j(render partial: 'likes/like', locals: {performance: @performance}) %>");

app/views/likes/destroy.js.erb
$('.likes_buttons').html("<%= j(render partial: 'likes/like', locals: {performance: @performance}) %>");