config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'
}
  root to: 'performances#index'
  get 'performances/search'
  get 'performances/privacy'
  get '/users', to: 'users#a'
  post '/user/guest_sign_in', to: 'users#new_guest'

  resources :performances do
    resources :likes, only: %i[create destroy]
  end
  resources :users, only: :show
  resources :inquiries, only: [:new, :create]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  with_options presence: true do
    validates :nickname
    validates :email, uniqueness: { case_sensitive: true }
    validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i }, confirmation: true
  end

  has_many :performances
  has_one_attached :image
  has_many :likes

  def self.from_omniauth(auth)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    unless user
      user = User.new(
        provider: auth.provider,
        uid: auth.uid,
        nickname: auth.info.name,
        name: auth.info.name,
        email: User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
      user.save(validate: false)

    end
    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: 'Facebook')
        end
    else
      session['devise.facebook_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end

  def twitter
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: 'Twitter')
        end
    else
      session['devise.twitter_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: 'Google')
        end
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end

  private

  def sign_up_params
    params.require(:user).permit(:uid, :provider, :name, :image_url, :password)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def show
    @nickname = current_user.nickname
    @performances = current_user.performances
    @user = User.find(params[:id])
    @performances_likes = @user.performances
    @likes = @user.likes
  end

  def a
    redirect_to new_user_registration_path
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
      user.nickname = 'ゲストユーザー'
    end
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/header" %>

<div class="mypage-content">
  <div class="mypage-title">
   <%= @nickname %>さんのマイページ
  </div>
  <div class="mypage-wrap">
      <div class="mypage-link-new">
        <%=link_to '公演情報を登録する', new_performance_path, class:"link-new-btn" %>
      </div>
      <div class="my-performances">
        <div class="my-performances-title">
        <%= image_tag('performance.png', class:"performance-logo", alt:"performance")%>
           登録した公演
           </div>
           <% @performances.each do |p| %>
             <li class="list">
               <%= link_to performance_path(p.id) do%>
                 <%= p.title %>
                 <%= p.group %>
               <% end %>
             </li>
           <% end %>
        </div>
        
      <div class="my-performances">
        <div class="my-performances-title">
        <%= image_tag('like.png', class:"performance-logo", alt:"performance")%>
           いいね！した公演
           </div>
           <% @likes.each do |like| %>
             <li class="list">
             <% performance = Performance.find_by(id: like.performance_id) %>
               <%= link_to performance_path(performance.id) do %>
                 <%= performance.title %>
                 <%= performance.group %>
               <% end %>
             </li>
           <% end %>

       </div>
  </div>
  <%= link_to 'トップページにもどる', root_path, class:"back-home" %>
</div>
<%= render "shared/footer" %>