config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks'
}
  root to: 'performances#index'
  get 'performances/search'
  get 'performances/privacy'
  get '/users', to: 'users#a'
  post '/user/guest_sign_in', to: 'users#new_guest'

  resources :performances do
    resources :likes, only: %i[create destroy]
  end
  resources :users, only: :show
  resources :inquiries, only: [:new, :create]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
   
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-content">
   <%= image_tag("IMG_6670.PNG",alt:'butaijin-logo',class:"footer-image")%>
    <div class="footer-text">Copyright (C) 2020 BUTAI-JIN, All Rights Reserved.</div>
    <p><%= link_to "プライバシーポリシー", performances_privacy_path, class:"privacy" %></p>
</div>

app/views/shared/_header.html.erb
<%#サイドメニュー%>
<nav class="navbar">
    <%= image_tag('list.png', class:"data-menu-toggle", alt:"list")%>
    <div class="navbar-menu" id="menu">
      <div class="navbar-menu-overlay" data-menu-toggle>
        <div class="navbar-menu-body">
          <ul class="navbar-link-list">
            <li class="navbar-link-item">
              Stearch!（舞台公演検索）
            </li>
            <% if user_signed_in? %>
             <li class="navbar-link-item">
              <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
             <li class="navbar-link-item">
              <%= link_to 'マイページ',"/users/#{current_user.id}"%>
            </li>
            <% else %>
              <li class="navbar-link-item">     
                <div class="login-show">ログイン</div>
              </li>
              <li class="navbar-link-item">
                <div class="signup-show">新規登録</div>
              </li>
            <% end %>
            <li class="navbar-link-item">
              <a class="item-link">スティーチの使い方▽</a>
              <ul class="sub-menu">
               <li>
               <p>都内でやっている舞台を</p>
               <p>ワンクリックで検索できます。</p>
               <p>条件を絞って検索もできます。</p>
               <p>公演情報はユーザー登録をして</p>
               <p>各団体が管理してください。</p>
               </li>
              </ul>
            </li>
            <li class="navbar-link-item">
              <a class="item-link">Q&A▽</a>
              <ul class="sub-menu">
                <p>Q.公演の登録はどうすれば？</p>
                <p>A.ユーザー登録をしてください。</p>
                <p>Q.登録画像が表示されない！</p>
                <p>A.画像を小さくしてみてください。</p>
                 <p>Q.ログインできなくなった。</p>
                 <p>A.アカウントを作り直してください。</p>
                 <p>Q.住所を編集しても地図のマーカーが変わらない</p>
                 <p>A.一度空にして更新をし、再度住所を記入してみてください。</p>
              </ul>
            </li>
            <li class="navbar-link-item">
              <a class="item-link">問合せ・不具合報告▽</a>
              <ul class="sub-menu">
              <%= link_to '問い合わせフォームへ',"/inquiries/new", id:"inquiries-btn"%>
               </ul>
            </li>
          </ul>
          <div class="close">
            <button class="data-menu-toggle" id="close-btn">CLOSE</button>
          </div>
          <div class="usagi-image">
            <%= image_tag('usagi.png',class:"navbar-usagi", alt: "usagi")%>
          </div>
        </div>
      </div>
    </div>
  </nav>
<%#/サイドメニュー%>

<div class="top-page-header">
  <div class="top-page-header-image">
   <div class=header-content>
      <%= link_to image_tag('logo.png', class:"header-logo", alt:"タイトル"),"/"%>
   <ul class="header-list">
    <% if user_signed_in? %>
      <li class="header-login">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"logout header-btn" %>
      </li>
      <li class="header-new">
        <%= link_to 'マイページ',"/users/#{current_user.id}", class: "user-nickname header-btn" %>
      </li>
    <% else %>
      <%= link_to 'ゲスト様' , user_guest_sign_in_path, class:"guest-login" , method: :post %>
      <li class="header-login">     
        <div class="login login-show header-btn">ログイン</div>
      </li>
      <li class="header-new">
        <div class="sign-up signup-show header-btn">新規登録</div>
      </li>
    <% end %>
    <div class="header-navi-wrap">
    <% if current_page?(root_path) %>
       <%= image_tag('navi.png', class:"header-navi",id:"header-navi", alt:"navi")%>
       <p class="navi-under" id="navi-under">公演の登録はこちら<p>
    <% end %>
    </div>
  </ul>
</div>
<%#新規登録モーダル%>
<div class="login-modal-wrap" id="modal-sign-up">
  <div class="modal">
    <div class="close-model">
       <div class="close-btn">✖️</div>
       </div>
       <div id="login-form">
         <h2>ユーザー登録</h2>
          <div class="modal-text">SNSアカウントで登録する</div>
            <div class="sns-wrap">
              <ul class="sns-btn">
                <li><%= link_to 'Facebook', user_facebook_omniauth_authorize_path, class:"fb-btn" %></li>
                <li><%= link_to 'Twitter', user_twitter_omniauth_authorize_path, class:"tw-btn" %></li>
                <li><%= link_to 'Google', user_google_oauth2_omniauth_authorize_path, class:"go-btn" %></li>
              </ul>
            </div>
            <div class="modal-mail-wrap">
            <%= link_to 'メールアドレスで新規登録', new_user_registration_path, class: "modal-mail-btn" %>
            </div>
       </div>
     </div>
  </div>
</div>
<%#/新規登録モーダル%>
<%#ログインモーダル%>
<div class="login-modal-wrap" id="modal-login">
<div class="modal">
 <div class="close-model">
      <div class="close-btn">✖️</div>
    </div>
      <div id="login-form">
        <h2>ログイン</h2>
          <div class="modal-text">SNSアカウントでログインする</div>
            <div class="sns-wrap">
              <ul class="sns-btn">
                <li><%= link_to 'Facebook', user_facebook_omniauth_authorize_path, class:"fb-btn" %></li>
                <li><%= link_to 'Twitter', user_twitter_omniauth_authorize_path, class:"tw-btn" %></li>
                <li><%= link_to 'Google', user_google_oauth2_omniauth_authorize_path, class:"go-btn" %></li>
              </ul>
            </div>
            <div class="modal-mail-wrap">
            <%= link_to 'メールアドレスでログイン', new_user_session_path, class: "modal-mail-btn" %>
            </div>
        </div>
      </div>
   </div>
</div>
<%#/ログインモーダル%>

app/views/shared/_notifications.html.erb
 <div class="set">
 </div> 
  <% flash.each do |key, value| %>
    <div class="flash">
    <%= content_tag(:div, value, class: "#{key}") %>
    </div>
  <% end %>